# Nome do seu workflow (opcional, mas recomendado)
name: CI/CD - Deploy FTP Locaweb

# Define quando o workflow será executado (gatilho/trigger)
# Exemplo: executar em push para a branch 'main'
on:
  push:
    branches: [ main ] # Ajuste para o nome da sua branch principal (pode ser 'master')
  # Você pode adicionar outros gatilhos, como pull_request, schedule, etc.
  # workflow_dispatch: # Permite disparar manualmente pela interface do GitHub

# Define os trabalhos (jobs) que serão executados no workflow
jobs:
  # Nome do job (você pode escolher qualquer nome)
  deploy-ftp:
    # O tipo de máquina virtual (runner) onde o job será executado
    runs-on: ubuntu-latest

    # Sequência de passos (steps) a serem executados neste job
    steps:
      # 1. Passo essencial: Fazer o checkout do código do seu repositório
      #    Para que o runner tenha acesso aos arquivos a serem enviados
      - name: Checkout repository code
        uses: actions/checkout@v4 # É recomendado usar uma versão específica

      # 2. O seu passo de deploy FTP
      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          # Host FTP (obrigatório) - Buscando do secrets do repositório
          host: ${{ secrets.HOST }}
          # Usuário FTP (obrigatório) - Buscando do secrets do repositório
          user: ${{ secrets.USER }}
          # Senha FTP (obrigatório) - Buscando do secrets do repositório
          password: ${{ secrets.PASS }}

          # --- Parâmetros Opcionais ---
          # Se você não precisar alterar os valores padrão, pode remover ou comentar estas linhas

          # Forçar conexão SSL (opcional, padrão: false)
          # forceSsl: false

          # Diretório local que será enviado (opcional, padrão: '.')
          # Seus arquivos da aplicação, '.' significa a raiz do repositório após o checkout
          # localDir: '.'

          # Diretório remoto no servidor FTP onde os arquivos serão enviados (opcional, padrão: 'public_html')
          # remoteDir: 'public_html' # Ou o caminho correto no seu FTP

          # Opções adicionais para o comando lftp (opcional, padrão: '')
          # Exemplo: '--delete' para remover arquivos no destino que não existem na origem
          # options: '--delete --verbose'