name: Deploy Next.js Static Export via FTP
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    name: Deploy Static Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Build Next.js App
        run: npm run build
      - name: Verify Build Output directory
        run: ls -la
      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with: 
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: "out"